# fly.toml - Fly.io configuration for PerFi Delta

app = 'perfi-delta'
primary_region = 'gru'

[build]

[deploy]
  # release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'perfi-delta.fly.dev'
  PORT = '8081'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[http_service.checks]]
  grace_period = "20s"
  interval = "15s"
  method = "GET"
  path = "/health"
  headers = { Host = "localhost" }
  timeout = "5s"

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
